import { MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import { Notifications } from "@mantine/notifications";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { theme } from "~/themes/default";
import "./globals.css";

const EuclidCircularB = localFont({
  src: [
    {
      path: "/fonts/EuclidCircularB-Regular.ttf",
      weight: "400",
      style: "Normal",
    },
    {
      path: "/fonts/EuclidCircularB-Medium.ttf",
      weight: "500",
      style: "Normal",
    },
    {
      path: "/fonts/EuclidCircularB-Bold.ttf",
      weight: "600",
      style: "Normal",
    },
  ],
  variable: "--font-EuclidCircularB",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${EuclidCircularB.variable}`}>
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Snowkap - OP</title>
        <link rel="icon" type="image/x-icon" href="vercel.svg" />
      </head>
      <body>
        <MantineProvider
          theme={theme}
          defaultColorScheme="light"
          forceColorScheme="light"
        >
          <Notifications position="top-right" mr={13} />
          <div>{children}</div>
        </MantineProvider>
      </body>
    </html>
  );
}
