export const FormFieldInterfaces = {
    datetime: "datetime",
    file: "file",
    "group-accordion": "group-accordion",
    "group-detail": "group-detail",
    "group-raw": "group-raw",
    "group-wizard": "group-wizard",
    "group-wizard-step": "group-wizard-step",
    "group-tabs": "group-tabs",
    input: "input",
    "input-autocomplete": "input-autocomplete",
    "input-auto-complete-api": "input-auto-complete-api",
    "input-multiline": "input-multiline",
    "input-rich-text": "input-rich-text",
    "presentation-divider": "presentation-divider",
    "presentation-notice": "presentation-notice",
    "presentation-links": "presentation-links",
    "select-dropdown": "select-dropdown",
    "select-multiple-dropdown": "select-multiple-dropdown",
    "select-radio": "select-radio",
    "select-toggle": "select-toggle",
    "select-multiple-checkbox": "select-multiple-checkbox",
    tags: "tags",
    badges: "badges",
    slider: "slider",
};
