[server]
headless = true

[client]
showErrorDetails = true
toolbarMode = "minimal"
hideSidebarNav = true

[theme]
base = "light"
primaryColor = "#38bdf8"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#f1f5f9"
textColor = "#1e293b"
font = "sans serif"
