export const AppGlobalMasterConstant = {
  address_activity_mappings: [
    {
      ownership_type: "Own",
      address_type: "Manufacturing",
      activities: [
        "general",
        "production",
        "energy",
        "transport",
        "waste",
        "buyer_share",
        "material",
        "capitalgoods",
        "water",
        "water_withdrawal",
        "fugitive",
        "csr_master",
        "humanresources",
        "healthandsafety",
        "boardandgovernance",
        "grievances",
        "product_share_allocation",
        "use_of_sold_products",
      ],
    },
    {
      ownership_type: "Contract",
      address_type: "Manufacturing",
      activities: [
        "general",
        "production",
        "energy",
        "transport",
        "waste",
        "buyer_share",
        "material",
        "capitalgoods",
        "water",
        "water_withdrawal",
        "fugitive",
        "csr_master",
        "humanresources",
        "healthandsafety",
        "boardandgovernance",
        "grievances",
        "product_share_allocation",
        "use_of_sold_products",
      ],
    },
    {
      ownership_type: "Own",
      address_type: "NonManufacturing",
      activities: [
        "general",
        "energy",
        "transport",
        "waste",
        "buyer_share",
        "material",
        "capitalgoods",
        "water",
        "water_withdrawal",
        "fugitive",
        "csr_master",
        "humanresources",
        "healthandsafety",
        "boardandgovernance",
        "grievances",
        "product_share_allocation",
        "use_of_sold_products",
      ],
    },
  ],
  activities: [
    "general",
    "production",
    "energy",
    "transport",
    "waste",
    "buyer_share",
    "material",
    "capitalgoods",
    "water",
    "water_withdrawal",
    "fugitive",
    "csr_master",
    "humanresources",
    "healthandsafety",
    "boardandgovernance",
    "grievances",
    "product_share_allocation",
    "use_of_sold_products",
  ],
} as const;
