query getDataImportHistory(
  $activityFilter: DataImportHistory_bool_exp
  $start: Int
  $size: Int
  $orderBy: [DataImportHistory_order_by!]
  $whereFilter: DataImportHistory_bool_exp!
) {
  DataImportHistory(
    where: $activityFilter
    offset: $start
    limit: $size
    order_by: $orderBy
  ) {
    file_name
    Activity {
      id
      name
    }
    OrganizationAddress {
      Organization {
        id
      }
      Address {
        id
        full_address
        name
        City {
          id
          name
        }
        State {
          id
          name
        }
      }
    }
    created_at
    AppUser {
      id
      name
      email
    }
    import_method
    status
    status_data
    file_url
  }
  totalCount: DataImportHistory_aggregate(where: $whereFilter) {
    aggregate {
      count
    }
  }
  activityTotalCount: DataImportHistory_aggregate(where: $activityFilter) {
    aggregate {
      count
    }
  }
  generalCount: DataImportHistory_aggregate(
    where: { _and: [{ Activity: { code: { _eq: "general" } } }, $whereFilter] }
  ) {
    aggregate {
      count
    }
  }
  productionCount: DataImportHistory_aggregate(
    where: {
      _and: [{ Activity: { code: { _eq: "production" } } }, $whereFilter]
    }
  ) {
    aggregate {
      count
    }
  }
  businessTravelCount: DataImportHistory_aggregate(
    where: {
      _and: [
        { Activity: { code: { _eq: "transport_business_travel" } } }
        $whereFilter
      ]
    }
  ) {
    aggregate {
      count
    }
  }
  employeeTravelCount: DataImportHistory_aggregate(
    where: {
      _and: [
        { Activity: { code: { _eq: "transport_employee_travel" } } }
        $whereFilter
      ]
    }
  ) {
    aggregate {
      count
    }
  }
  energyCaptivePowerCount: DataImportHistory_aggregate(
    where: {
      _and: [
        { Activity: { code: { _eq: "energy_captive_power" } } }
        $whereFilter
      ]
    }
  ) {
    aggregate {
      count
    }
  }
  energyGridCount: DataImportHistory_aggregate(
    where: {
      _and: [{ Activity: { code: { _eq: "energy_grid_power" } } }, $whereFilter]
    }
  ) {
    aggregate {
      count
    }
  }
  fuelPurchageGridCount: DataImportHistory_aggregate(
    where: {
      _and: [
        { Activity: { code: { _eq: "energy_fuel_purchased" } } }
        $whereFilter
      ]
    }
  ) {
    aggregate {
      count
    }
  }
  wasteCount: DataImportHistory_aggregate(
    where: { _and: [{ Activity: { code: { _eq: "waste" } } }, $whereFilter] }
  ) {
    aggregate {
      count
    }
  }
  BuyerShareCount: DataImportHistory_aggregate(
    where: {
      _and: [{ Activity: { code: { _eq: "buyer_share" } } }, $whereFilter]
    }
  ) {
    aggregate {
      count
    }
  }

  UpstreamCount: DataImportHistory_aggregate(
    where: {
      _and: [
        { Activity: { code: { _eq: "transport_upstream" } } }
        $whereFilter
      ]
    }
  ) {
    aggregate {
      count
    }
  }
  DownstreamCount: DataImportHistory_aggregate(
    where: {
      _and: [
        { Activity: { code: { _eq: "transport_downstream" } } }
        $whereFilter
      ]
    }
  ) {
    aggregate {
      count
    }
  }
  MaterialCount: DataImportHistory_aggregate(
    where: {
      _and: [
        { Activity: { code: { _eq: "material_procurement" } } }
        $whereFilter
      ]
    }
  ) {
    aggregate {
      count
    }
  }

  CsrCount: DataImportHistory_aggregate(
    where: { _and: [{ Activity: { code: { _eq: "csr" } } }, $whereFilter] }
  ) {
    aggregate {
      count
    }
  }

  governanceAndBoardCompositionCount: DataImportHistory_aggregate(
    where: {
      _and: [
        { Activity: { code: { _eq: "governance_and_board_composition" } } }
        $whereFilter
      ]
    }
  ) {
    aggregate {
      count
    }
  }

  humanResourceCount: DataImportHistory_aggregate(
    where: {
      _and: [{ Activity: { code: { _eq: "human_resources" } } }, $whereFilter]
    }
  ) {
    aggregate {
      count
    }
  }

  healthAndSafetyCount: DataImportHistory_aggregate(
    where: {
      _and: [{ Activity: { code: { _eq: "health_and_safety" } } }, $whereFilter]
    }
  ) {
    aggregate {
      count
    }
  }
  wasteWaterGenerationCount: DataImportHistory_aggregate(
    where: {
      _and: [
        { Activity: { code: { _eq: "wastewater_generation" } } }
        $whereFilter
      ]
    }
  ) {
    aggregate {
      count
    }
  }

  waterWithdrawalCount: DataImportHistory_aggregate(
    where: {
      _and: [{ Activity: { code: { _eq: "water_withdrawal" } } }, $whereFilter]
    }
  ) {
    aggregate {
      count
    }
  }

  wasteWaterTreatment: DataImportHistory_aggregate(
    where: {
      _and: [
        { Activity: { code: { _eq: "waste_water_treatment" } } }
        $whereFilter
      ]
    }
  ) {
    aggregate {
      count
    }
  }

  waterConumptionCount: DataImportHistory_aggregate(
    where: {
      _and: [{ Activity: { code: { _eq: "water_consumption" } } }, $whereFilter]
    }
  ) {
    aggregate {
      count
    }
  }

  FugitiveDetailsCount: DataImportHistory_aggregate(
    where: {
      _and: [{ Activity: { code: { _eq: "fugitive_details" } } }, $whereFilter]
    }
  ) {
    aggregate {
      count
    }
  }

  GrievancesCount: DataImportHistory_aggregate(
    where: {
      _and: [
        { Activity: { code: { _eq: "grievances_activity" } } }
        $whereFilter
      ]
    }
  ) {
    aggregate {
      count
    }
  }
}
