query getMaterialMasterWithPagination(
  $where: OrgMaterialMaster_bool_exp!
  $limit: Int
  $offset: Int
  $order_by: [OrgMaterialMaster_order_by!]
) {
  OrgMaterialMaster(where: $where, order_by: $order_by, limit: $limit, offset: $offset) {
    id
    client_master_id
    name
    code
    type
    organization_id
    Material_Weight_Per_Unit
    UoM_Material_Weight
    Material_Description
    Material_Classification
    Additional_Information
    created_at
    updated_at
    is_deleted
  }
  totalMaterialsCount: OrgMaterialMaster_aggregate(where: $where) {
    aggregate {
      totalRows: count
    }
  }
}
