query getSupplierMaterialMappig($organizationId: uuid!) {
  SupplierMaterialMapping(
    where: { organization_id: { _eq: $organizationId } }
  ) {
    id
    organization_id
    supplier_address_mapping_id
    org_material_master_id
    From_Year
    From_Month
    To_Year
    To_Month
    meta_data
  }
}
