query GetAddressesByLocationCodeAndName(
  $locationName: String
  $organizationId: uuid
) {
  OrganizationAddress(
    where: {
      organization_id: { _eq: $organizationId }
      Address: { name: { _ilike: $locationName } }
    }
  ) {
    Address {
      is_deleted
      metadata
      latitude
      longitude
      client_master_id
      code
      facility_type
      full_address
      name
      ownership_type
      pincode
      type
      created_at
      updated_at
      city_id
      country_id
      created_by
      id
      state_id
      updated_by
    }
  }
}
