query getGHGTransportWasteManagementByTaskRequest($task_request_id: [uuid!]!) {
  GHGWaste(where: { task_request_id: { _in: $task_request_id } }) {
    id
    organization_address_id
    task_request_id
    activity_task_request_id
    Types_of_Waste_Generated
    Waste_Disposal_Managed_by
    Quantity_of_Waste
    Quantity_of_Waste_UoM
    Disposal_Mechanism
    Name_of_Third_Party
    Location_of_Waste_Disposal
    Location_pin_or_zip_code
    Mode_of_Transport
    Who_Managed_Transportation_of_Waste
    Vehicle_Type_Used_for_Road_Transport
    Fuel_Used
    DistOf_WasteDisposalLoction_from_FacilityLocation
    DistOf_WasteDisposalLoction_from_FacilityLocation_UoM
    supporting_docs
    kpi_DistanceTravlled_For_WasteManagement
    kpi_DistanceTravlled_For_WasteManagement_uom
    kpi_em_EmissionBy_TransportFor_WasteManagement
    kpi_emf_EmissionBy_TransportFor_WasteManagement
    kpi_em_EmissionBy_Generation_of_Waste_Type
    kpi_emf_EmissionBy_Generation_of_Waste_Type
    updated_at
    updated_by

    created_at
    created_by

    TaskRequest {
      month
      year
    }
    OrganizationAddress {
      Address {
        country_id
        Country {
          region_code
        }
      }
    }
  }
}
