query getTransportUpstreamData($task_request_id: [uuid!]!) {
  GHGTransport_Upstream(where: { task_request_id: { _in: $task_request_id } }) {
    id
    activity_task_request_id
    organization_address_id
    task_request_id
    Material_ID
    Material_Procured
    Supplier_code
    Supplier_Status
    Locations_Procured_From
    Transport_Managed_by
    Mode_of_Transport
    Third_Party_Suppliers_of_Material
    Vehicle_Type_Used_for_Road_Transport
    Fuel_Used
    Location_pin_or_zip_code
    Material_Quantity_Procured
    Material_Quantity_Procured_uom
    Distance_per_Trip
    Distance_per_Trip_uom
    Number_of_Trips
    Quantity_of_Fuel_Consumed
    Quantity_of_Fuel_Consumed_uom
    kpi_Distance_Travelled_uom
    kpi_em_EmissionBy_TravelledDistance
    kpi_emf_EmissionBy_TravelledDistance
    created_at
    updated_at
    created_by
    updated_by
    kpi_em_EmissionBy_MaterialProcured
    kpi_emf_EmissionBy_MaterialProcured
    kpi_Distance_Travelled
    supporting_docs
    TaskRequest {
      month
      year
    }
    OrganizationAddress {
      Address {
        country_id
        Country {
          region_code
        }
      }
    }
  }
}
