query getESGHealthAndSafetyByPeriod(
  $fromDate: date!
  $toDate: date!
  $organizationId: uuid!
) {
  poc_view_esg_health_and_safety(
    where: {
      period_date: { _gte: $fromDate, _lte: $toDate }
      organization_id: { _eq: $organizationId }
    }
    order_by: { period_date: asc }
  ) {
    organization_id
    year
    month
    period_date
    workforce_category
    total_lost_time_injuries
    total_hours_worked
  }
}
