import { FormFieldInterfaces } from "./types";

export const InterfaceDefaultOptions: FormFieldInterfaces = {
  default: {} as any,
  "select-toggle": {
    type: "boolean",
    fieldOptions: {
      label: "",
      enable: true,
      readonly: false,
      required: false,
    },
    interfaceOptions: {
      showLabel: false,
      title: "",
      size: "md",
      onLabel: "Yes",
      offLabel: "No",
      subtitle: "",
    },
    display: "",
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "group-wizard": {
    field: "",
    fieldOptions: {
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      template: "wizard1" as "wizard1",
      showControls: false,
    },
    display: "",
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "group-wizard-step": {
    field: "",
    fieldOptions: {
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      title: "",
      breadcrumb: "",
      subtitle: "",
    },
    display: "",
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "group-wizard-sub-step": {
    field: "",
    fieldOptions: {
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      title: "",
      subtitle: "",
    },
    display: "",
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "group-tabs": {
    field: "",
    fieldOptions: {
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      template: "pagination" as "pagination",
      showControls: true,
    },
    display: "",
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "select-radio": {
    field: "",
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      showLabel: false,
      title: "",
      choices: [],
      subtitle: "",
    },
    display: "",
    displayOptions: {
      orientation: "vertical" as "horizontal" | "vertical",
    },
    displayRules: [],
    validationRules: [],
  },
  "select-dropdown": {
    field: "",
    fieldOptions: {
      label: "If yes, Specify certification ?",
      enable: true,
      readonly: false,
      required: false,
    },
    interfaceOptions: {
      showLabel: false,
      title: "",
      apiUrl: "",
      choices: [],
      defaultValue: "ISO 14001",
      placeholder: "Select",
      subtitle: "",
    },
    display: "",
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  datetime: {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      showLabel: false,
      title: "",
      placeholder: "",
      isRange: false,
      fromDate: new Date(),
      toDate: new Date(),
      subtitle: "",
    },
    displayOptions: {
      format: "",
    },
    displayRules: [],
    validationRules: [],
  },
  file: {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      showLabel: false,
      title: "",
      accept: ["application/pdf"],
      allowMultiple: true,
      maxFilesCount: 5,
      maxSizeInMb: 2,
      subtitle: "",
    },
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "group-accordion": {
    fieldOptions: {
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      title: "",
      subtitle: "",
    },
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "group-detail": {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      title: "",
      showTitleDivider: false,
      spacing: 5,
      columns: {
        lg: 1,
        md: 1,
        sm: 1,
        xs: 1,
      },
      subtitle: "",
    },
    displayOptions: {
      orientation: "vertical",
    },
    displayRules: [],
    validationRules: [],
  },
  "group-raw": {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {},
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  input: {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      showLabel: false,
      title: "",
      placeholder: "",
      isHeading: false,
      headingSize: "",
      showTitleDivider: false,
      subtitle: "",
      isToolTip: false,
      isemail: false,
      isAlphabetSpecialChar: false,
      isHyperLink: false,
      isAdvance: false,
    },
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "number-input": {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      showLabel: false,
      title: "",
      placeholder: "",
      isHeading: false,
      headingSize: "",
      showTitleDivider: false,
      subtitle: "",
    },
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "input-autocomplete": {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      showLabel: false,
      title: "",
      placeholder: "",
    },
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "input-auto-complete-api": {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      showLabel: false,
      title: "",
      placeholder: "",
    },
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "input-multiline": {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      showLabel: false,
      title: "",
      placeholder: "",
      autosize: false,
      maxRows: 4,
      minRows: 3,
      maxColumns: 50,
      maxLength: 255,
      subtitle: "",
      isHyperLink: false,
    },
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "input-rich-text": {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      showLabel: false,
      placeholder: "",
      title: "",
      subtitle: "",
    },
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "presentation-divider": {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {},
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "presentation-notice": {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {},
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "presentation-links": {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {},
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "select-multiple-dropdown": {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      showLabel: false,
      title: "",
      placeholder: "",
      choices: [],
      creatable: false,
      searchable: false,
      maxSelectedValues: 0,
      subtitle: "",
    },
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "selected-multiple-dropdown": {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      showLabel: false,
      title: "",
      placeholder: "",
      choices: [],
      creatable: false,
      searchable: false,
      maxSelectedValues: 0,
      subtitle: "",
    },
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "select-multiple-checkbox": {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      showLabel: false,
      title: "",
      placeholder: "",
      choices: [],
      subtitle: "",
    },
    displayOptions: {
      orientation: "vertical",
    },
    displayRules: [],
    validationRules: [],
  },
  tags: {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      showLabel: false,
    },
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  badges: {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      showLabel: false,
    },
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  slider: {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      showLabel: false,
      title: "",
    },
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  label: {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {},
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  monthyear: {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      showLabel: false,
      title: "",
      placeholder: "",
      isHeading: false,
      headingSize: "",
      showTitleDivider: false,
      subtitle: "",
      isToolTip: false,
      isemail: false,
      isAlphabetSpecialChar: false,
      isHyperLink: false,
      isAutoCalculate: false,
    },
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "multi-select-row": {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      showLabel: false,
      title: "",
      placeholder: "",
      choices: [],
      creatable: false,
      searchable: false,
      maxSelectedValues: 0,
      subtitle: "",
    },
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
  "fixed-question-table": {
    fieldOptions: {
      label: "",
      required: false,
      enable: true,
      readonly: false,
    },
    interfaceOptions: {
      showLabel: false,
      title: "",
      placeholder: "",
      choices: [],
      creatable: false,
      searchable: false,
      maxSelectedValues: 0,
      subtitle: "",
      header: [],
      footer: [],
      isAutoCalculate: false
    },
    displayOptions: {},
    displayRules: [],
    validationRules: [],
  },
};

type InterfaceTypesRec = Record<
  keyof FormFieldInterfaces,
  keyof FormFieldInterfaces
>;

export const FormFieldInterfacesData: InterfaceTypesRec = Object.keys(
  InterfaceDefaultOptions
).reduce((acc, curr, i) => {
  acc[curr] = curr;
  return acc;
}, {} as any);

export { FormFieldInterfacesData as FormFieldInterfaces };

