query GetCompanyStatusMaster($companyStatusGuid: uuid!) {
  Tbl_CompanyStatusMaster(where: {CompanyStatusGuid: {_eq: $companyStatusGuid}}) {
    CompanyStatusGuid
    CompanyStatusName
    RoleGuid
  }
}