query GetUserDetailsByPasswordToken($SetPasswordToken: String!) {
  Tbl_Users(where: { SetPasswordToken: { _eq: $SetPasswordToken } }) {
    UserGuid
    EmailId
    MobileNumber
    FirstName
    LastName
    IsActive
    CompanyName
    Password
    CreatedDate
    SetPasswordToken
    OPSUserId
  }
}
