query GetPasswordManageMasterByEmail($email: String!) {
  Tbl_PasswordManageMaster(where: {EmailId: {_eq: $email}}, order_by: {CreatedDate: desc}) {
    EmailId
    Password
    CreatedDate
    PasswordCreateDate
  }
}
