query GetCountryMaster {
  Tbl_CountryMaster(where: {StatusForSupplier: {_eq: true}}) {
    CountryGuid
    CountryName
    CountryCode
    Image
    MobileCode
    RegionGuid
    IsActive
    StatusForSupplier
  }
}
