query GetUserByMobile($mobile: String) {
  Tbl_Users(
    where: {
      _and: [
        { MobileNumber: { _eq: $mobile } }
        { IsActive: { _eq: true } }
        { IsDeleted: { _eq: false } }
      ]
    }
  ) {
    UserGuid
    EmailId
    MobileNumber
    FirstName
    LastName
    CpanelUserId
    OPSUserId
    Tbl_UserRoleMappings:Tbl_UserRoleMappings_userGuid  {
      RoleGuid
      Tbl_Role {
        RoleGuid
        RoleName
        IsActive
        CreatedDateUtc
      }
      Tbl_UserStatusMaster {
        StatusGuid
        Status
      }
    }
    IsVerified
    Password
    CreatedDate
    Tbl_UserCompanyMappings {
      CompanyGuid
      Tbl_Company {
        Tbl_CompanyRoleMappings {
          RoleGuid
          StatusGuid
          Tbl_CompanyStatusMaster {
            CompanyStatusGuid
            CompanyStatusName
          }
        }
      }
    }
  }
}
