query GetMaterialProcurementsByMonthYearOrgAddressIds(
  $whereCondition: TaskRequest_bool_exp!
  $supplier_codes: [String!]
) {
  TaskRequest(where: $whereCondition) {
    id
    month
    year
    organization_address_id
    GHGMaterialProcurements(
      where: { Supplier_Code: { _in: $supplier_codes } }
    ) {
      task_request_id
      Supplier_Code
      Material_Quantity_Procured
      Material_Quantity_Procured_uom
      organization_address_id
    }
  }
}
