query getGHGMaterialProcurementDataByTaskRequestIdsOrgWithSupplierMasterData(
  $whereYearMonths: TaskRequest_bool_exp!
  $supplierName: String!
) {
  TaskRequest(where: $whereYearMonths) {
    month
    year
    GHGMaterialProcurements {
      id
      activity_task_request_id
      organization_address_id
      task_request_id
      Material_Code
      Supplier_Code
      Material_Quantity_Procured
      Material_Quantity_Procured_uom
      kpi_em_EmissionBy_MaterialProcured
      kpi_emf_EmissionBy_MaterialProcured
      created_at
      updated_at
      created_by
      updated_by
      supporting_docs
    }
  }

  OrgSupplierMaster(where: { name: { _eq: $supplierName } }) {
    id
    code
    name
  }
}
