query getCaptivePowerNonRenewableFuelById($id: uuid!) {
  GHGEnergy_CaptivePower_NonRenewable(where: { id: { _eq: $id } }) {
    id
    Type_of_Fuel_Used
    Quantity_of_fuel_consumed
    Quantity_of_fuel_consumed_uom
    Quality_of_fuel
    Unit_of_Energy_Generated_in_Kwh
    supporting_docs
    kpi_em_Emission_EnergyGenerated_kwh
    kpi_emf_Emission_EnergyGenerated_kwh
    GHGEnergyConsumption_CaptivePower_id
    created_by
    updated_by
    GHGEnergy_CaptivePower {
      id
      task_request_id
      Type_of_Captive_Power
      organization_address_id
      Do_You_Generate_Captive_Power_for_Own_Use
      TaskRequest {
        id
        year
        month
        organization_address_id
      }
    }
  }
}
