query getOrganizationSecretKey {
  AppGlobalMaster(
    where: {
      _and: [
        { type: { _eq: "organization-config" } }
        { sub_type: { _eq: "secret-key" } }
        { key: { _eq: "ce25acad-8602-4c9f-9365-ebf4ac2d5a8e" } }
      ]
    }
  ) {
    key
    data
  }
}
