query getMaterialMasterByCodes($where: OrgMaterialMaster_bool_exp!) {
  OrgMaterialMaster(where: $where) {
    id
    name
    code
    type
    Material_Weight_Per_Unit
    UoM_Material_Weight
    Material_Classification
    Material_Description
    Additional_Information
    organization_id
  }
}
