query getESGRenewableElectricityConsumption(
  $fromDate: date!
  $toDate: date!
  $organizationId: uuid!
) {
  poc_view_electricity_consumption_renewable(
    where: {
      period_date: { _gte: $fromDate, _lte: $toDate }
      organization_id: { _eq: $organizationId }
    }
    order_by: { period_date: asc }
  ) {
    organization_id
    year
    month
    period_date
    consumption
  }
}
